<?php
/**
 * plugins.php
 */

if( function_exists('acf_add_local_field_group') ) {

	acf_add_local_field_group(array(
		'key' => 'group_5e7a278cc0ce0',
		'title' => 'Hide content',
		'fields' => array(
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'acf_after_title',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'the_content',
		),
		'active' => true,
		'description' => '',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ec81366c8590',
		'title' => 'Hero',
		'fields' => array(
			array(
				'key' => 'field_5ec81d9551014',
				'label' => 'Instellingen van hero',
				'name' => 'hero',
				'type' => 'group',
				'instructions' => 'De hero is de plaat bovenaan de pagina waar een afbeelding, titel en beschrijving kan staan.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => 'acf-hero-grid',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ec8136d92f34',
						'label' => 'Titel van pagina',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'Plaats hier de titel van deze pagina. Als je dit veld leeg laat dan wordt de titel hierboven gebruikt als titel.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => 'acf-hero-grid-title',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5ec813b692f35',
						'label' => 'Inleiding van pagina',
						'name' => 'intro',
						'type' => 'wysiwyg',
						'instructions' => 'Plaats hier de inleiding van deze pagina. Dit veld is optioneel.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => 'acf-hero-grid-intro',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5ece378285511',
						'label' => 'Afbeelding van pagina',
						'name' => 'thumbnail',
						'type' => 'image',
						'instructions' => 'Kies de afbeelding voor deze pagina.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => 'acf-hero-grid-thumbnail',
							'id' => '',
						),
						'return_format' => 'array',
						'preview_size' => 'full',
						'library' => 'all',
						'min_width' => '',
						'min_height' => '',
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page_type',
					'operator' => '!=',
					'value' => 'front_page',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'Page, Post',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ee0aad40a474',
		'title' => 'Hero Voorpagina',
		'fields' => array(
			array(
				'key' => 'field_5ee0aad40f400',
				'label' => 'Instellingen van hero',
				'name' => 'hero',
				'type' => 'group',
				'instructions' => 'De hero is de plaat bovenaan de pagina waar een afbeelding, titel en beschrijving kan staan.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => 'acf-hero-grid',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ee0aad410adf',
						'label' => 'Inleiding van pagina',
						'name' => 'intro',
						'type' => 'wysiwyg',
						'instructions' => 'Plaats hier de inleiding van deze pagina. Dit veld is optioneel.',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => 'acf-hero-grid-intro',
							'id' => '',
						),
						'default_value' => '',
						'tabs' => 'all',
						'toolbar' => 'basic',
						'media_upload' => 0,
						'delay' => 0,
					),
					array(
						'key' => 'field_5ee0aad410ae4',
						'label' => 'Achtergrond instellingen',
						'name' => 'background',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => 'acf-hero-grid-thumbnail',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ee0ab76fb018',
								'label' => 'Kies tussen video of afbeelding als achtergrond',
								'name' => 'type',
								'type' => 'radio',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'choices' => array(
									'image' => 'Afbeelding',
									'video' => 'Video',
								),
								'allow_null' => 0,
								'other_choice' => 0,
								'default_value' => 'image',
								'layout' => 'horizontal',
								'return_format' => 'value',
								'save_other_choice' => 0,
							),
							array(
								'key' => 'field_5ee0ab9dfb019',
								'label' => 'Selecteer de afbeelding voor de achtergrond.',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5ee0ab76fb018',
											'operator' => '==',
											'value' => 'image',
										),
									),
								),
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
							array(
								'key' => 'field_5ee0abc4fb01a',
								'label' => 'Selecteer de video voor de achtergrond',
								'name' => 'video',
								'type' => 'file',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => array(
									array(
										array(
											'field' => 'field_5ee0ab76fb018',
											'operator' => '==',
											'value' => 'video',
										),
									),
								),
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'library' => 'all',
								'min_size' => '',
								'max_size' => '',
								'mime_types' => '.mp4, .ogv, .webm',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 5,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'Front page',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ed8eee849ef4',
		'title' => 'Layout',
		'fields' => array(
			array(
				'key' => 'field_5ed8eef19adf7',
				'label' => 'Layout',
				'name' => 'layout',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5ed8ef06b2c3e' => array(
						'key' => 'layout_5ed8ef06b2c3e',
						'name' => 'text',
						'label' => 'Tekst',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ed8ef379adfb',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ee2069183e72' => array(
						'key' => 'layout_5ee2069183e72',
						'name' => 'text-image',
						'label' => 'Tekst + Afbeelding',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ee206a083e73',
								'label' => 'Instellingen',
								'name' => 'settings',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ee206b083e74',
										'label' => 'Volgorde van layout',
										'name' => 'order',
										'type' => 'button_group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'large: Afbeelding links, tekst rechts' => 'large: Afbeelding links, tekst rechts',
											'large-reverse' => 'Tekst links, afbeelding rechts',
										),
										'allow_null' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
								),
							),
							array(
								'key' => 'field_5ee2070183e75',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5ee2073f83e76',
								'label' => 'Afbeelding instellingen',
								'name' => 'image',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ee21b3c76a36',
										'label' => 'Kies afbeelding uit mediabibliotheek',
										'name' => 'file',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'full',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5ee21c6b00209',
										'label' => 'Toon onderschrift van afbeelding',
										'name' => 'caption',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 1,
										'ui_on_text' => 'Ja',
										'ui_off_text' => 'Nee',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ed8ef259adf8' => array(
						'key' => 'layout_5ed8ef259adf8',
						'name' => 'image',
						'label' => 'Afbeelding',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ed8ef889adfc',
								'label' => 'Kies afbeelding',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'full',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ed8ef339adfa' => array(
						'key' => 'layout_5ed8ef339adfa',
						'name' => 'video',
						'label' => 'Video',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ed8efa69adfd',
								'label' => 'Video instellingen',
								'name' => 'video',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ed8f0249adfe',
										'label' => 'Kies een bron',
										'name' => 'source',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'local' => 'Bestand uit mediabibliotheek',
											'external' => 'Video van externe bron',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'default_value' => 'local',
										'layout' => 'horizontal',
										'return_format' => 'value',
										'save_other_choice' => 0,
									),
									array(
										'key' => 'field_5ed8f0a19adff',
										'label' => 'Kies video uit mediabibliotheek',
										'name' => 'video_local',
										'type' => 'file',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5ed8f0249adfe',
													'operator' => '==',
													'value' => 'local',
												),
											),
										),
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'library' => 'all',
										'min_size' => '',
										'max_size' => '',
										'mime_types' => '.mp4, .ogv, .webm',
									),
									array(
										'key' => 'field_5ed8f1619ae00',
										'label' => 'Plak link van externe video',
										'name' => 'video_external',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5ed8f0249adfe',
													'operator' => '==',
													'value' => 'external',
												),
											),
										),
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5eda198eb7e28' => array(
						'key' => 'layout_5eda198eb7e28',
						'name' => 'gallery',
						'label' => 'Gallerij',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5eda199cb7e29',
								'label' => 'Voeg afbeelding toe uit de mediabibliotheek.',
								'name' => 'gallery',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'insert' => 'append',
								'library' => 'all',
								'min' => '',
								'max' => '',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Voeg layout blok toe',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
				),
				array(
					'param' => 'page_type',
					'operator' => '!=',
					'value' => 'front_page',
				),
			),
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/about.php',
				),
			),
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/contact.php',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 15,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'Default template',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ef24fc40a771',
		'title' => 'Layout Setup',
		'fields' => array(
			array(
				'key' => 'field_5ef24fd1d19fb',
				'label' => 'Layout',
				'name' => 'layout-setup',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5ef24ff030fb1' => array(
						'key' => 'layout_5ef24ff030fb1',
						'name' => 'text',
						'label' => 'Tekst',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef2586130a8f',
								'label' => 'Kop van blok',
								'name' => 'head',
								'type' => 'group',
								'instructions' => 'Vul hier de titel en inleiding in van dit blok. Deze komt bovenaan dit blok te staan.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef2588030a90',
										'label' => 'Titel',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef2588f30a91',
										'label' => 'Inleiding',
										'name' => 'intro',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
								),
							),
							array(
								'key' => 'field_5ef2501bd19fc',
								'label' => 'Inhoud van blok',
								'name' => 'content',
								'type' => 'wysiwyg',
								'instructions' => 'Vul hier de inhoudelijke tekst van dit blok in.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef2503ad19fd' => array(
						'key' => 'layout_5ef2503ad19fd',
						'name' => 'image',
						'label' => 'Afbeelding',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef2503fd19fe',
								'label' => 'Kies afbeelding',
								'name' => 'image',
								'type' => 'image',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'library' => 'all',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef25082d19ff' => array(
						'key' => 'layout_5ef25082d19ff',
						'name' => 'details',
						'label' => 'Details',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef258cdc0e44',
								'label' => 'Kop van blok',
								'name' => 'head',
								'type' => 'group',
								'instructions' => 'Vul hier de titel en inleiding in van dit blok. Deze komt bovenaan dit blok te staan.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef258cdc0e45',
										'label' => 'Titel',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef258cdc0e46',
										'label' => 'Inleiding',
										'name' => 'intro',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
								),
							),
							array(
								'key' => 'field_5ef2508ad1a00',
								'label' => 'Details setup',
								'name' => 'details',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Detail toevoegen',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef255e5d1a01',
										'label' => 'Label van detail',
										'name' => 'label',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '75',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef27ca96fc56',
										'label' => 'ID van label',
										'name' => 'id',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '25',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef255f8d1a02',
										'label' => 'Inhoud van detail',
										'name' => 'content',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef9f60cc8a4b' => array(
						'key' => 'layout_5ef9f60cc8a4b',
						'name' => 'text-image',
						'label' => 'Tekst + Afbeelding',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef9f5a2ab828',
								'label' => 'Instellingen',
								'name' => 'settings',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef9f5a2ab829',
										'label' => 'Volgorde van layout',
										'name' => 'order',
										'type' => 'button_group',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'large: Afbeelding links, tekst rechts' => 'large: Afbeelding links, tekst rechts',
											'large-reverse' => 'Tekst links, afbeelding rechts',
										),
										'allow_null' => 0,
										'default_value' => '',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
								),
							),
							array(
								'key' => 'field_5ef9f5a2ab82a',
								'label' => 'Content',
								'name' => 'content',
								'type' => 'wysiwyg',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
							array(
								'key' => 'field_5ef9f5a2ab82b',
								'label' => 'Afbeelding instellingen',
								'name' => 'image',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '50',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef9f5a2ab82c',
										'label' => 'Kies afbeelding uit mediabibliotheek',
										'name' => 'file',
										'type' => 'image',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'preview_size' => 'full',
										'library' => 'all',
										'min_width' => '',
										'min_height' => '',
										'min_size' => '',
										'max_width' => '',
										'max_height' => '',
										'max_size' => '',
										'mime_types' => '',
									),
									array(
										'key' => 'field_5ef9f5a2ab82d',
										'label' => 'Toon onderschrift van afbeelding',
										'name' => 'caption',
										'type' => 'true_false',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '50',
											'class' => '',
											'id' => '',
										),
										'message' => '',
										'default_value' => 0,
										'ui' => 1,
										'ui_on_text' => 'Ja',
										'ui_off_text' => 'Nee',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef9f638c8a4c' => array(
						'key' => 'layout_5ef9f638c8a4c',
						'name' => 'video',
						'label' => 'Video',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef9f5a2ab82f',
								'label' => 'Video instellingen',
								'name' => 'video',
								'type' => 'group',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef9f5a2ab830',
										'label' => 'Kies een bron',
										'name' => 'source',
										'type' => 'radio',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'choices' => array(
											'local' => 'Bestand uit mediabibliotheek',
											'external' => 'Video van externe bron',
										),
										'allow_null' => 0,
										'other_choice' => 0,
										'save_other_choice' => 0,
										'default_value' => 'local',
										'layout' => 'horizontal',
										'return_format' => 'value',
									),
									array(
										'key' => 'field_5ef9f5a2ab831',
										'label' => 'Kies video uit mediabibliotheek',
										'name' => 'video_local',
										'type' => 'file',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5ef9f5a2ab830',
													'operator' => '==',
													'value' => 'local',
												),
											),
										),
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
										'library' => 'all',
										'min_size' => '',
										'max_size' => '',
										'mime_types' => '.mp4, .ogv, .webm',
									),
									array(
										'key' => 'field_5ef9f5a2ab832',
										'label' => 'Plak link van externe video',
										'name' => 'video_external',
										'type' => 'oembed',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => array(
											array(
												array(
													'field' => 'field_5ef9f5a2ab830',
													'operator' => '==',
													'value' => 'external',
												),
											),
										),
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'width' => '',
										'height' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef9f654c8a4e' => array(
						'key' => 'layout_5ef9f654c8a4e',
						'name' => 'gallery',
						'label' => 'Gallerij',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef9f5a2ab833',
								'label' => 'Voeg afbeelding toe uit de mediabibliotheek.',
								'name' => 'gallery',
								'type' => 'gallery',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'return_format' => 'array',
								'preview_size' => 'medium',
								'insert' => 'append',
								'library' => 'all',
								'min' => '',
								'max' => '',
								'min_width' => '',
								'min_height' => '',
								'min_size' => '',
								'max_width' => '',
								'max_height' => '',
								'max_size' => '',
								'mime_types' => '',
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Voeg layout blok toe',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/setup.php',
				),
			),
		),
		'menu_order' => 15,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'setup',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5eeb98f16861a',
		'title' => 'Layout Voorpagina',
		'fields' => array(
			array(
				'key' => 'field_5eeb9924c72aa',
				'label' => 'Layout',
				'name' => 'layout-front-page',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '100',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'layout_5ef0757e8fd9c' => array(
						'key' => 'layout_5ef0757e8fd9c',
						'name' => 'text',
						'label' => 'Tekst',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef0758f8fd9d',
								'label' => 'Kop van blok',
								'name' => 'head',
								'type' => 'group',
								'instructions' => 'Vul hier de titel en inleiding in van dit blok. Deze komt bovenaan dit blok te staan.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef078728fdad',
										'label' => 'Titel',
										'name' => 'title',
										'type' => 'text',
										'instructions' => 'Titel van dit blok.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef078868fdae',
										'label' => 'Inleiding',
										'name' => 'intro',
										'type' => 'textarea',
										'instructions' => 'Inleiding van dit blok.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
								),
							),
							array(
								'key' => 'field_5ef075a58fd9e',
								'label' => 'Inhoud van blok',
								'name' => 'content',
								'type' => 'wysiwyg',
								'instructions' => 'Vul hier de inhoudelijke tekst van dit blok in.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'tabs' => 'all',
								'toolbar' => 'full',
								'media_upload' => 0,
								'delay' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5eeb995756959' => array(
						'key' => 'layout_5eeb995756959',
						'name' => 'navigation',
						'label' => 'Site navigatie',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5eeb99fbc72ab',
								'label' => 'Voeg navigatieblok toe',
								'name' => 'navigation_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Voeg item toe',
								'sub_fields' => array(
									array(
										'key' => 'field_5eeb9a52c72ad',
										'label' => 'Titel van blok',
										'name' => 'title',
										'type' => 'text',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5eeb9a68c72ae',
										'label' => 'Beschrijving van pagina',
										'name' => 'description',
										'type' => 'textarea',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
									array(
										'key' => 'field_5eeb9a3ac72ac',
										'label' => 'Link naar pagina',
										'name' => 'link',
										'type' => 'link',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'return_format' => 'array',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef076098fd9f' => array(
						'key' => 'layout_5ef076098fd9f',
						'name' => 'timeline',
						'label' => 'Tijdlijn',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef078ea8fdb2',
								'label' => 'Kop van blok',
								'name' => 'head',
								'type' => 'group',
								'instructions' => 'Vul hier de titel en inleiding in van dit blok. Deze komt bovenaan dit blok te staan.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef078ea8fdb3',
										'label' => 'Titel',
										'name' => 'title',
										'type' => 'text',
										'instructions' => 'Titel van dit blok.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef078ea8fdb4',
										'label' => 'Inleiding',
										'name' => 'intro',
										'type' => 'textarea',
										'instructions' => 'Inleiding van dit blok.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
								),
							),
							array(
								'key' => 'field_5ef076548fda3',
								'label' => 'Over de tijdlijn.',
								'name' => '',
								'type' => 'message',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'message' => 'De items in de tijdlijn kunnen aangepast worden in het <strong>Berichten</strong> menu.',
								'new_lines' => 'wpautop',
								'esc_html' => 0,
							),
						),
						'min' => '',
						'max' => '',
					),
					'layout_5ef0769e8fda4' => array(
						'key' => 'layout_5ef0769e8fda4',
						'name' => 'map',
						'label' => 'Kaart',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef078f88fdb5',
								'label' => 'Kop van blok',
								'name' => 'head',
								'type' => 'group',
								'instructions' => 'Vul hier de titel en inleiding in van dit blok. Deze komt bovenaan dit blok te staan.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef078f88fdb6',
										'label' => 'Titel',
										'name' => 'title',
										'type' => 'text',
										'instructions' => 'Titel van dit blok.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef078f88fdb7',
										'label' => 'Inleiding',
										'name' => 'intro',
										'type' => 'textarea',
										'instructions' => 'Inleiding van dit blok.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '100',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'maxlength' => '',
										'rows' => 3,
										'new_lines' => 'br',
									),
								),
							),
							array(
								'key' => 'field_5ef076a28fda6',
								'label' => 'Kaart',
								'name' => 'map',
								'type' => 'group',
								'instructions' => 'Vul hier de instellingen van de kaart in.',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'layout' => 'block',
								'sub_fields' => array(
									array(
										'key' => 'field_5ef077408fda7',
										'label' => 'Access Token',
										'name' => 'access_token',
										'type' => 'text',
										'instructions' => 'Vul hier de Access Token in voor de kaart. Deze token is nodig om de kaart te laden.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => 'pk.eyJ1IjoibWlsb3NhdXJ1cyIsImEiOiJja2FzM2NobmEwbGRiMnFxZm1rNG0ydDFnIn0.1chjWNs_Eom2MgUF-nfS3w',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef0774e8fda8',
										'label' => 'Stijl van map',
										'name' => 'map_style',
										'type' => 'text',
										'instructions' => 'Vul hier de stijl van de map in van Mapbox.com.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => 'mapbox://styles/milosaurus/cka9ntnsf1fcl1jpd759hdudv',
										'placeholder' => 'mapbox://styles/',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_5ef077938fda9',
										'label' => 'Middenpunt van kaart',
										'name' => 'center',
										'type' => 'group',
										'instructions' => 'Kies het middenpunt van de kaart met lengte- en breedtegraden.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'layout' => 'block',
										'sub_fields' => array(
											array(
												'key' => 'field_5ef077a48fdaa',
												'label' => 'Lengtegraad',
												'name' => 'latitude',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '52.846529',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
											array(
												'key' => 'field_5ef077b88fdab',
												'label' => 'Breedtegraad',
												'name' => 'longitude',
												'type' => 'text',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '50',
													'class' => '',
													'id' => '',
												),
												'default_value' => '4.753624',
												'placeholder' => '',
												'prepend' => '',
												'append' => '',
												'maxlength' => '',
											),
										),
									),
									array(
										'key' => 'field_5ef077cc8fdac',
										'label' => 'Zoom niveau',
										'name' => 'zoom',
										'type' => 'text',
										'instructions' => 'Kies het zoom niveau om op te beginnen.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => 15,
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Voeg layout blok toe',
				'min' => '',
				'max' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array(
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
				),
			),
		),
		'menu_order' => 15,
		'position' => 'normal',
		'style' => 'seamless',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'Front page',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ef09263bc02b',
		'title' => 'Sociale links',
		'fields' => array(
			array(
				'key' => 'field_5ef09274e92c3',
				'label' => 'Voeg sociale links toe',
				'name' => 'social_links',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ef0928ae92c4',
						'label' => 'LinkedIn',
						'name' => 'linkedin',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'member',
				),
			),
		),
		'menu_order' => 15,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'member',
	));
	
	acf_add_local_field_group(array(
		'key' => 'group_5ece177aa52f6',
		'title' => 'Contact',
		'fields' => array(
			array(
				'key' => 'field_5ece17939334f',
				'label' => 'Instellingen van contactgegevens',
				'name' => 'contact',
				'type' => 'group',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layout' => 'block',
				'sub_fields' => array(
					array(
						'key' => 'field_5ece17a493350',
						'label' => 'Telefoonnummer',
						'name' => 'phone',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_5ece19ea93353',
						'label' => 'Emailadres',
						'name' => 'email',
						'type' => 'link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'return_format' => 'array',
					),
					array(
						'key' => 'field_5ece1a1993356',
						'label' => 'Adres',
						'name' => 'address',
						'type' => 'group',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '100',
							'class' => 'acf-contact-grid',
							'id' => '',
						),
						'layout' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_5ef9b91e1c39b',
								'label' => 'Straat',
								'name' => 'street',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'acf-contact-grid-street',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ef9b92d1c39c',
								'label' => 'Huisnummer',
								'name' => 'number',
								'type' => 'number',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => 'acf-contact-grid-number',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'min' => '',
								'max' => '',
								'step' => '',
							),
							array(
								'key' => 'field_5ece1a3d93358',
								'label' => 'Postcode',
								'name' => 'postal_code',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => 'acf-contact-grid-postal-code',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_5ece1a4c93359',
								'label' => 'Plaats',
								'name' => 'city',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '100',
									'class' => 'acf-contact-grid-city',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
						),
					),
				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'templates/contact.php',
				),
			),
		),
		'menu_order' => 20,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'contact',
	));
	
}